export const OBTENER_PRODUCTOS_EXITO = 'OBTENER_PRODUCTOS';
export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO';
export const CONFIRMAR_ORDEN_PEDIDO = 'CONFIRMAR_ORDEN_PEDIDO';
export const MOSTRAR_RESUMEN = 'MOSTRAR_RESUMEN';
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';
export const PEDIDO_ORDENADO = 'PEDIDO_ORDENADO';